[project]
name = "wallet_generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bip32utils>=0.3.post4",
    "mnemonic>=0.21",
    "pykeepass>=4.1.1.post1",
    "tronpy>=0.6.1",
]

[project.scripts]
tron = "wallet_generator.tron.__main__:main"


[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
